### ISSUE TITLE
dotnet_publish task passes invalid switch to msbuild

### ISSUE THREAD

**Issue by jrshoare** [RobinHerbots/grunt-dotnet#2]
I am using grunt-dotnet version 0.0.9.

In my gruntfile I have the following task configuration:

```js
dotnet_publish: {
    webapi_simulator: {
        options: {
           name: 'webapi.simulator'
        },
        src: ['../../modules/WebApi.Simulator/WebApi.Simulator.csproj']
    }
}
```

(I had to browse the source code to find that the `name` option is required).

However, when I invoke grunt with the verbose option (`-v`) for the task I get the following output:

```
Running "dotnet_publish:webapi_simulator" (dotnet_publish) task
Verifying property dotnet_publish.webapi_simulator exists in config...OK
Files: ../../modules/WebApi.Simulator/WebApi.Simulator.csproj
Options: name="webapi.simulator"
Options: name="webapi.simulator"
Options: verbose, dryRun=undefined, name="webapi.simulator"
MSBuild version 17.4.1+fedecea9d for .NET
MSBUILD : error MSB1001: Unknown switch.
    Full command line: 'C:\Program Files\dotnet\sdk\7.0.103\MSBuild.dll -maxcpucount -verbosity:m -restore -target:Publish --property:_IsPublishing=true -Name webapi.simulator -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\7.0.103\dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,C:\Program Files\dotnet\sdk\7.0.103\dotnet.dll'
  Switches appended by response files:
Switch: -Name

For switch syntax, type "MSBuild -help"
Fatal error: Error running dotnet_publish
```

This seems to pass `-Name` to msbuild which is not a valid switch and does not pass down the project specified in the `src` property.

**Comment by RobinHerbots** [comment]
@jrshoare ,

I will have a look at the switches for publish.  And/Or if you can send a PR with a fix or update in the readme, that is always very welcome.

**Comment by RobinHerbots** [comment]
@jrshoare , 

I updated the publish command.  

Todo: add some unittest + publish

**Comment by RobinHerbots** [comment]
@jrshoare ,

Can you have a try with latest.  Also check the readme for the options.

**Comment by jrshoare** [comment]
That works a treat. I also had a look at the README and was happy to see the list of supported options.

Thanks for the rapid fix 👍!
